string = "AAAGACGAACTAAACACTCTGTGTCAAAGACGAAAAGACGAGGCCGTCGGCCGTCAAAGACGAGGCCGTCAAAGACGAGGCCGTCAAAGACGAGGCCGTCACTAAACACAAAGACGACCGACACGAACTAAACACACTAAACACTCTGTGTCTCTGTGTCACTAAACACTCTGTGTCGGCCGTCTCTGTGTCGGCCGTCGGCCGTCGGCCGTCAAAGACGAAAAGACGAACTAAACACTCTGTGTCAAAGACGACCGACACGAACTAAACACACTAAACACACTAAACACAAAGACGACCGACACGAACTAAACACAAAGACGATCTGTGTCGGCCGTCGGCCGTCGGCCGTCTCTGTGTCACTAAACACACTAAACACGGCCGTCAAAGACGACCGACACGATCTGTGTCTCTGTGTCGGCCGTCAAAGACGACCGACACGATCTGTGTCCCGACACGAACTAAACACACTAAACACTCTGTGTCACTAAACACACTAAACACGGCCGTCACTAAACACGGCCGTCCCGACACGATCTGTGTCACTAAACACGGCCGTCCCGACACGAAAAGACGATCTGTGTCAAAGACGAAAAGACGAGGCCGTCGGCCGTCGGCCGTCAAAGACGACCGACACGAAAAGACGAGGCCGTCTCTGTGTCAAAGACGAACTAAACACGGCCGTCGGCCGTCTCTGTGTCCCGACACGACCGACACGAGGCCGTCTCTGTGTCTCTGTGTCAAAGACGAACTAAACACCCGACACGAACTAAACACGGCCGTCACTAAACACCCGACACGATCTGTGTCGGCCGTCGGCCGTCAAAGACGACCGACACGATCTGTGTCACTAAACACAAAGACGATCTGTGTCCCGACACGA"
def patternCount(string, pattern, k):
	count = 0
	for i in range(0, (len(string) - k + 1)): 
		if(string[i:i+k] == pattern):
			count +=1
	return count

def frequencyWords(string, k):
	count = []
	frequentPatterns = []
	for i in range(0, (len(string) - k + 1)):
		pattern = string[i:i + k]
		count.append(patternCount(string,pattern, k))
	maxCount = max(count)
	for i in range(0, (len(string) - k  + 1)):
		if count[i] == maxCount:
			frequentPatterns.append(string[i: i + k])
	frequentPatterns = set(frequentPatterns)
	return frequentPatterns

result = frequencyWords(string, 13)
print result

